preset: symfony

finder:
    path:
        - "src"
        - "tests"

enabled:
    - short_array_syntax

disabled:
    - concat_without_spaces
    - trailing_comma_in_multiline_array
    - unalign_double_arrow
    - phpdoc_annotation_without_dot
